"""debug

Revision ID: 180ac732fb73
Revises: b3091889f668
Create Date: 2026-04-23 15:22:11.303838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180ac732fb73'
down_revision: Union[str, Sequence[str], None] = 'b3091889f668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_tasks_id'), table_name='reminder_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reminder_tasks_id'), 'reminder_tasks', ['id'], unique=False)
    # ### end Alembic commands ###
