"""add push_subscriptions

Revision ID: a02b4998cfc3
Revises: 180ac732fb73
Create Date: 2026-04-23 15:57:22.056321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a02b4998cfc3'
down_revision: Union[str, Sequence[str], None] = '180ac732fb73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('medications_user_id_fkey'), 'medications', type_='foreignkey')
    op.create_foreign_key(None, 'medications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('reminder_tasks', sa.Column('is_notified', sa.Boolean(), nullable=True))
    op.alter_column('reminder_tasks', 'time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('reminder_tasks_medication_id_fkey'), 'reminder_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'reminder_tasks', 'medications', ['medication_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminder_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('reminder_tasks_medication_id_fkey'), 'reminder_tasks', 'medications', ['medication_id'], ['id'])
    op.alter_column('reminder_tasks', 'time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('reminder_tasks', 'is_notified')
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.create_foreign_key(op.f('medications_user_id_fkey'), 'medications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
