"""update medication table

Revision ID: b3091889f668
Revises: b348f5525215
Create Date: 2026-04-23 14:46:50.435406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3091889f668'
down_revision: Union[str, Sequence[str], None] = 'b348f5525215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'raw_ocr_data')
    op.drop_column('medications', 'schedule_pattern')
    op.drop_column('medications', 'start_time')
    op.drop_column('medications', 'frequency_type')
    op.drop_column('medications', 'end_time')
    op.drop_column('medications', 'reminder_times')
    op.add_column('reminder_tasks', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('reminder_tasks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.drop_column('reminder_tasks', 'scheduled_at')
    op.drop_column('reminder_tasks', 'is_taken')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder_tasks', sa.Column('is_taken', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('reminder_tasks', sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('reminder_tasks', 'is_completed')
    op.drop_column('reminder_tasks', 'time')
    op.add_column('medications', sa.Column('reminder_times', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('medications', sa.Column('frequency_type', postgresql.ENUM('DAILY', 'WEEKLY', 'INTERVAL', name='frequencytype'), autoincrement=False, nullable=True))
    op.add_column('medications', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('schedule_pattern', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('medications', sa.Column('raw_ocr_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
