"""add medicine table

Revision ID: b348f5525215
Revises: 78e96fd18b2f
Create Date: 2026-04-22 15:18:51.337803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b348f5525215'
down_revision: Union[str, Sequence[str], None] = '78e96fd18b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('raw_ocr_data', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('frequency_type', sa.Enum('DAILY', 'WEEKLY', 'INTERVAL', name='frequencytype'), nullable=True),
    sa.Column('schedule_pattern', sa.JSON(), nullable=True),
    sa.Column('reminder_times', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('is_taken', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_tasks_id'), 'reminder_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_tasks_id'), table_name='reminder_tasks')
    op.drop_table('reminder_tasks')
    op.drop_table('medications')
    # ### end Alembic commands ###
